### ISSUE TITLE
dudley: test_mesh_dump_to_NetCDF_brick

### ISSUE THREAD

**Issue by aellery** [LutzGross/esys-escript.github.io#27]
The tests test_mesh_dump_to_NetCDF_brick and test_mesh_dump_to_NetCDF_rectangle are failing for dudley on the buildbot gnu-hyb-py3-paso-long.

**Comment by LutzGross** [comment]
dudley will be removed

**Comment by LutzGross** [comment]
dudley has been remove in version 6
